In [1]:
import cv2 
import numpy as np

In [2]:
# HAAR Cascade files
cascade_eye = '/haarcascade_eye.xml'
cascade_face ='/haarcascade_frontalface_alt.xml'

In [3]:
face_classifier = cv2.CascadeClassifier(cascade_face)
eye_classifier = cv2.CascadeClassifier(cascade_eye)

In [4]:
# Reading images and converting to grayscale
image = cv2.imread(r'/Caterina_Murino_1.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [5]:
# Detecting faces
faces = face_classifier.detectMultiScale(gray, 1.3, 5)
print (faces)

[[351 149 365 365]]


In [6]:
if faces.any():
    for (x, y, w, h) in faces:
        print (len(faces))
        cv2.rectangle(image, (x, y), (x+w, y+h), (0,0,0), 3)
        cv2.imshow("Face Detection", image)
        cv2.waitKey(0)

        # Cropping the face found
        area_gray = gray[y:y+h, x:x+w]
        area_original = image[y:y+h, x:x+w]

        # Detecting eyes
        eyes = eye_classifier.detectMultiScale(area_gray)
        print (eyes)
        print (len(eyes))
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(area_original, (ex, ey), (ex+ew, ey+eh), (0,255,0), 2)
            cv2.imshow("Face Detection", image)
            cv2.waitKey(0)
            
elif faces is ():
    print ("No Faces Found")

cv2.destroyAllWindows()

1
[[ 61  94  83  83]
 [206 118  53  53]
 [124 122  46  46]]
3
